### ISSUE TITLE
Nested route and (Nested)HyperlinkedModelSerializer

### ISSUE THREAD

**Issue by zacbri** [alanjds/drf-nested-routers#119]
Hi,

Nested routes work fine with ModelSerializer as described in Readme, but we'd like to use Hyperlinked serializers.  
The HyperlinkedModelSerializer fails at building the url field as expected, so I gave the NestedHyperlinkedModelSerializer a try.  
Using your example:

```python
# urls.py

router = routers.SimpleRouter()
router.register(r'domains', DomainViewSet)

domains_router = routers.NestedSimpleRouter(router, r'domains', lookup='domain')
domains_router.register(r'nameservers', NameserverViewSet, base_name='domain-nameservers')

urlpatterns = patterns('',
    url(r'^', include(router.urls)),
    url(r'^', include(domains_router.urls)),
)
```

```python
# views.py

class NameserverViewSet(NestedHyperlinkedModelSerializer):
    model = Nameserver
    serializer_class = NestedNameserverSerializer

    def get_queryset(self):
        return Nameserver.objects.filter(domain=self.kwargs['domain_pk'])

```

```python
# serializers.py

class NameserverSerializer(NestedHyperlinkedModelSerializer):
    parent_lookup_kwargs = {
        'domain_pk': 'domain__pk',
    }

    class Meta:
        model = Nameserver
        fields = ('url', ...)

```

However, NestedHyperlinkedModelSerializer relies on DRF to generate the view_name, simply adding parent_lookup_kwargs to field_kwargs (see [here](https://github.com/alanjds/drf-nested-routers/blob/master/rest_framework_nested/serializers.py#L32), [here](https://github.com/encode/django-rest-framework/blob/f148e4e2593e55c76c746c85422924c33ec435cc/rest_framework/serializers.py#L1292) and [here](https://github.com/encode/django-rest-framework/blob/master/rest_framework/utils/field_mapping.py#L289)).  
And it fails since it tries to reverse `nameserver-detail` instead of `domain-nameservers-detail`

Is there a reason why this is done this way?

We've subclassed NestedHyperlinkedModelSerializer for now to work around this issue, but I'm wondering whether it might be worth a PR ?  
Here is what we use for now, but there might be a better way to handle it:

```python
# serializers.py

class CustomNestedNameserverSerializer(NestedHyperlinkedModelSerializer):
    def build_url_field(self, field_name, model_class):
        field_class, field_kwargs = super().build_url_field(
            field_name, model_class)
        if hasattr(self, 'url_view_name'):
            field_kwargs['view_name'] = self.url_view_name
        return field_class, field_kwargs


class NameserverSerializer(CustomNestedNameserverSerializer):
    parent_lookup_kwargs = {
        'domain_pk': 'domain__pk',
    }
    url_view_name = 'domain-nameservers-detail'

    class Meta:
        model = Nameserver
        fields = ('url', ...)
```

**Comment by alanjds** [comment]
For me is very positive to have such PR.

Can you please provide a test showing the wrong behavior?

**Comment by alanjds** [comment]
Are you trying with the `master`?  I just released it to the PyPI. Can you confirm please?

**Comment by jwaggs** [comment]
I can confirm that this issue is still an issue with the live version: 0.91. Just ran into this.

**Comment by alanjds** [comment]
Can you please issue a PR for it?

**Comment by jwaggs** [comment]
I will open a PR for it if I ever fix the underlying issue, but I have no current plan to do so... I have switched to a dotnet core web api for the time being and will not be working with django routes for the foreseeable future.
